//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Middleware.Proxy.CustomEbankit.EbankitCustomService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceInputHeader", Namespace="http://schemas.datacontract.org/2004/07/eBankit.Business.Entities")]
    [System.SerializableAttribute()]
    public partial class ServiceInputHeader : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccessSourceValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApplicationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Middleware.Proxy.CustomEbankit.EbankitCustomService.TransactionExecutionData ExecutionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InteractionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InteractionTypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ReadOnlyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecurityTokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SessionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccessSourceValue {
            get {
                return this.AccessSourceValueField;
            }
            set {
                if ((object.ReferenceEquals(this.AccessSourceValueField, value) != true)) {
                    this.AccessSourceValueField = value;
                    this.RaisePropertyChanged("AccessSourceValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Application {
            get {
                return this.ApplicationField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicationField, value) != true)) {
                    this.ApplicationField = value;
                    this.RaisePropertyChanged("Application");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Middleware.Proxy.CustomEbankit.EbankitCustomService.TransactionExecutionData ExecutionData {
            get {
                return this.ExecutionDataField;
            }
            set {
                if ((object.ReferenceEquals(this.ExecutionDataField, value) != true)) {
                    this.ExecutionDataField = value;
                    this.RaisePropertyChanged("ExecutionData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InteractionId {
            get {
                return this.InteractionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.InteractionIdField, value) != true)) {
                    this.InteractionIdField = value;
                    this.RaisePropertyChanged("InteractionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InteractionTypeId {
            get {
                return this.InteractionTypeIdField;
            }
            set {
                if ((this.InteractionTypeIdField.Equals(value) != true)) {
                    this.InteractionTypeIdField = value;
                    this.RaisePropertyChanged("InteractionTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language {
            get {
                return this.LanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageField, value) != true)) {
                    this.LanguageField = value;
                    this.RaisePropertyChanged("Language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ReadOnly {
            get {
                return this.ReadOnlyField;
            }
            set {
                if ((this.ReadOnlyField.Equals(value) != true)) {
                    this.ReadOnlyField = value;
                    this.RaisePropertyChanged("ReadOnly");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestId {
            get {
                return this.RequestIdField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestIdField, value) != true)) {
                    this.RequestIdField = value;
                    this.RaisePropertyChanged("RequestId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecurityToken {
            get {
                return this.SecurityTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.SecurityTokenField, value) != true)) {
                    this.SecurityTokenField = value;
                    this.RaisePropertyChanged("SecurityToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SessionId {
            get {
                return this.SessionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionIdField, value) != true)) {
                    this.SessionIdField = value;
                    this.RaisePropertyChanged("SessionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransactionExecutionData", Namespace="http://schemas.datacontract.org/2004/07/eBankit.Business.Entities")]
    [System.SerializableAttribute()]
    public partial class TransactionExecutionData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Middleware.Proxy.CustomEbankit.EbankitCustomService.TransactionAuthenticationData AuthenticationDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CloseOperationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CloseOperationWithSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CredentialTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FavoritIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSimulationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SendToStoreAndForwardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SendToWorkflowField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Middleware.Proxy.CustomEbankit.EbankitCustomService.TransactionAuthenticationData AuthenticationData {
            get {
                return this.AuthenticationDataField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthenticationDataField, value) != true)) {
                    this.AuthenticationDataField = value;
                    this.RaisePropertyChanged("AuthenticationData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CloseOperation {
            get {
                return this.CloseOperationField;
            }
            set {
                if ((this.CloseOperationField.Equals(value) != true)) {
                    this.CloseOperationField = value;
                    this.RaisePropertyChanged("CloseOperation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CloseOperationWithSuccess {
            get {
                return this.CloseOperationWithSuccessField;
            }
            set {
                if ((this.CloseOperationWithSuccessField.Equals(value) != true)) {
                    this.CloseOperationWithSuccessField = value;
                    this.RaisePropertyChanged("CloseOperationWithSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CredentialType {
            get {
                return this.CredentialTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.CredentialTypeField, value) != true)) {
                    this.CredentialTypeField = value;
                    this.RaisePropertyChanged("CredentialType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FavoritId {
            get {
                return this.FavoritIdField;
            }
            set {
                if ((object.ReferenceEquals(this.FavoritIdField, value) != true)) {
                    this.FavoritIdField = value;
                    this.RaisePropertyChanged("FavoritId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSimulation {
            get {
                return this.IsSimulationField;
            }
            set {
                if ((this.IsSimulationField.Equals(value) != true)) {
                    this.IsSimulationField = value;
                    this.RaisePropertyChanged("IsSimulation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OperationId {
            get {
                return this.OperationIdField;
            }
            set {
                if ((object.ReferenceEquals(this.OperationIdField, value) != true)) {
                    this.OperationIdField = value;
                    this.RaisePropertyChanged("OperationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SendToStoreAndForward {
            get {
                return this.SendToStoreAndForwardField;
            }
            set {
                if ((this.SendToStoreAndForwardField.Equals(value) != true)) {
                    this.SendToStoreAndForwardField = value;
                    this.RaisePropertyChanged("SendToStoreAndForward");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SendToWorkflow {
            get {
                return this.SendToWorkflowField;
            }
            set {
                if ((this.SendToWorkflowField.Equals(value) != true)) {
                    this.SendToWorkflowField = value;
                    this.RaisePropertyChanged("SendToWorkflow");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransactionAuthenticationData", Namespace="http://schemas.datacontract.org/2004/07/eBankit.Business.Entities")]
    [System.SerializableAttribute()]
    public partial class TransactionAuthenticationData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecurityCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecurityMaskField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecurityCode {
            get {
                return this.SecurityCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SecurityCodeField, value) != true)) {
                    this.SecurityCodeField = value;
                    this.RaisePropertyChanged("SecurityCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecurityMask {
            get {
                return this.SecurityMaskField;
            }
            set {
                if ((object.ReferenceEquals(this.SecurityMaskField, value) != true)) {
                    this.SecurityMaskField = value;
                    this.RaisePropertyChanged("SecurityMask");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceOutputHeader", Namespace="ITCore")]
    [System.SerializableAttribute()]
    public partial class ServiceOutputHeader : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Middleware.Proxy.CustomEbankit.EbankitCustomService.ServiceError ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FavoritIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasReturnMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastTransactionCallField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NextSecurityTokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OperationTypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Middleware.Proxy.CustomEbankit.EbankitCustomService.ServiceExecutionPerfomance PerfomanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Middleware.Proxy.CustomEbankit.EbankitCustomService.ServiceProgress ProgressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool RefreshAccountsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReturnCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReturnMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Middleware.Proxy.CustomEbankit.EbankitCustomService.SimulationResult SimulationResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<Middleware.Proxy.CustomEbankit.EbankitCustomService.ServiceStatus> StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VersionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Middleware.Proxy.CustomEbankit.EbankitCustomService.ServiceError Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FavoritId {
            get {
                return this.FavoritIdField;
            }
            set {
                if ((object.ReferenceEquals(this.FavoritIdField, value) != true)) {
                    this.FavoritIdField = value;
                    this.RaisePropertyChanged("FavoritId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasReturnMessage {
            get {
                return this.HasReturnMessageField;
            }
            set {
                if ((this.HasReturnMessageField.Equals(value) != true)) {
                    this.HasReturnMessageField = value;
                    this.RaisePropertyChanged("HasReturnMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastTransactionCall {
            get {
                return this.LastTransactionCallField;
            }
            set {
                if ((this.LastTransactionCallField.Equals(value) != true)) {
                    this.LastTransactionCallField = value;
                    this.RaisePropertyChanged("LastTransactionCall");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NextSecurityToken {
            get {
                return this.NextSecurityTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.NextSecurityTokenField, value) != true)) {
                    this.NextSecurityTokenField = value;
                    this.RaisePropertyChanged("NextSecurityToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OperationId {
            get {
                return this.OperationIdField;
            }
            set {
                if ((object.ReferenceEquals(this.OperationIdField, value) != true)) {
                    this.OperationIdField = value;
                    this.RaisePropertyChanged("OperationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OperationTypeId {
            get {
                return this.OperationTypeIdField;
            }
            set {
                if ((this.OperationTypeIdField.Equals(value) != true)) {
                    this.OperationTypeIdField = value;
                    this.RaisePropertyChanged("OperationTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Middleware.Proxy.CustomEbankit.EbankitCustomService.ServiceExecutionPerfomance Perfomance {
            get {
                return this.PerfomanceField;
            }
            set {
                if ((object.ReferenceEquals(this.PerfomanceField, value) != true)) {
                    this.PerfomanceField = value;
                    this.RaisePropertyChanged("Perfomance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Middleware.Proxy.CustomEbankit.EbankitCustomService.ServiceProgress Progress {
            get {
                return this.ProgressField;
            }
            set {
                if ((object.ReferenceEquals(this.ProgressField, value) != true)) {
                    this.ProgressField = value;
                    this.RaisePropertyChanged("Progress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool RefreshAccounts {
            get {
                return this.RefreshAccountsField;
            }
            set {
                if ((this.RefreshAccountsField.Equals(value) != true)) {
                    this.RefreshAccountsField = value;
                    this.RaisePropertyChanged("RefreshAccounts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReturnCode {
            get {
                return this.ReturnCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnCodeField, value) != true)) {
                    this.ReturnCodeField = value;
                    this.RaisePropertyChanged("ReturnCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReturnMessage {
            get {
                return this.ReturnMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnMessageField, value) != true)) {
                    this.ReturnMessageField = value;
                    this.RaisePropertyChanged("ReturnMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Middleware.Proxy.CustomEbankit.EbankitCustomService.SimulationResult SimulationResult {
            get {
                return this.SimulationResultField;
            }
            set {
                if ((object.ReferenceEquals(this.SimulationResultField, value) != true)) {
                    this.SimulationResultField = value;
                    this.RaisePropertyChanged("SimulationResult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<Middleware.Proxy.CustomEbankit.EbankitCustomService.ServiceStatus> Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Version {
            get {
                return this.VersionField;
            }
            set {
                if ((object.ReferenceEquals(this.VersionField, value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceError", Namespace="http://schemas.datacontract.org/2004/07/eBankit.Business.Entities")]
    [System.SerializableAttribute()]
    public partial class ServiceError : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Middleware.Proxy.CustomEbankit.EbankitCustomService.ServiceException ExField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<Middleware.Proxy.CustomEbankit.EbankitCustomService.ExceptionType> TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Middleware.Proxy.CustomEbankit.EbankitCustomService.ServiceException Ex {
            get {
                return this.ExField;
            }
            set {
                if ((object.ReferenceEquals(this.ExField, value) != true)) {
                    this.ExField = value;
                    this.RaisePropertyChanged("Ex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<Middleware.Proxy.CustomEbankit.EbankitCustomService.ExceptionType> Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceExecutionPerfomance", Namespace="http://schemas.datacontract.org/2004/07/eBankit.Business.Entities")]
    [System.SerializableAttribute()]
    public partial class ServiceExecutionPerfomance : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Middleware.Proxy.CustomEbankit.EbankitCustomService.ServiceExecutionPerfomance[] StepsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TotalExecutionTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime End {
            get {
                return this.EndField;
            }
            set {
                if ((this.EndField.Equals(value) != true)) {
                    this.EndField = value;
                    this.RaisePropertyChanged("End");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Start {
            get {
                return this.StartField;
            }
            set {
                if ((this.StartField.Equals(value) != true)) {
                    this.StartField = value;
                    this.RaisePropertyChanged("Start");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Middleware.Proxy.CustomEbankit.EbankitCustomService.ServiceExecutionPerfomance[] Steps {
            get {
                return this.StepsField;
            }
            set {
                if ((object.ReferenceEquals(this.StepsField, value) != true)) {
                    this.StepsField = value;
                    this.RaisePropertyChanged("Steps");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TotalExecutionTime {
            get {
                return this.TotalExecutionTimeField;
            }
            set {
                if ((this.TotalExecutionTimeField.Equals(value) != true)) {
                    this.TotalExecutionTimeField = value;
                    this.RaisePropertyChanged("TotalExecutionTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceProgress", Namespace="http://schemas.datacontract.org/2004/07/eBankit.Business.Entities")]
    [System.SerializableAttribute()]
    public partial class ServiceProgress : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProcessIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Middleware.Proxy.CustomEbankit.EbankitCustomService.ServiceProgressStatus StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProcessId {
            get {
                return this.ProcessIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ProcessIdField, value) != true)) {
                    this.ProcessIdField = value;
                    this.RaisePropertyChanged("ProcessId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Middleware.Proxy.CustomEbankit.EbankitCustomService.ServiceProgressStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SimulationResult", Namespace="ITCore")]
    [System.SerializableAttribute()]
    public partial class SimulationResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Middleware.Proxy.CustomEbankit.EbankitCustomService.AliasPositionsWithSession AliasPositionsWithSessionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DefaultCredentialTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool RequiresAuthenticationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] SuportedCredentialTypesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Middleware.Proxy.CustomEbankit.EbankitCustomService.AliasPositionsWithSession AliasPositionsWithSession {
            get {
                return this.AliasPositionsWithSessionField;
            }
            set {
                if ((object.ReferenceEquals(this.AliasPositionsWithSessionField, value) != true)) {
                    this.AliasPositionsWithSessionField = value;
                    this.RaisePropertyChanged("AliasPositionsWithSession");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DefaultCredentialType {
            get {
                return this.DefaultCredentialTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.DefaultCredentialTypeField, value) != true)) {
                    this.DefaultCredentialTypeField = value;
                    this.RaisePropertyChanged("DefaultCredentialType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool RequiresAuthentication {
            get {
                return this.RequiresAuthenticationField;
            }
            set {
                if ((this.RequiresAuthenticationField.Equals(value) != true)) {
                    this.RequiresAuthenticationField = value;
                    this.RaisePropertyChanged("RequiresAuthentication");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] SuportedCredentialTypes {
            get {
                return this.SuportedCredentialTypesField;
            }
            set {
                if ((object.ReferenceEquals(this.SuportedCredentialTypesField, value) != true)) {
                    this.SuportedCredentialTypesField = value;
                    this.RaisePropertyChanged("SuportedCredentialTypes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceStatus", Namespace="http://schemas.datacontract.org/2004/07/eBankit.Business.Entities")]
    public enum ServiceStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ok = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NOk = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PENDING = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceException", Namespace="http://schemas.datacontract.org/2004/07/eBankit.Business.Entities")]
    [System.SerializableAttribute()]
    public partial class ServiceException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Collections.Generic.KeyValuePair<object, object>[] _DataField;
        
        private string _HelpLinkField;
        
        private Middleware.Proxy.CustomEbankit.EbankitCustomService.ServiceException _InnerExceptionField;
        
        private string _MessageField;
        
        private string _SourceField;
        
        private string _StackTraceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.KeyValuePair<object, object>[] _Data {
            get {
                return this._DataField;
            }
            set {
                if ((object.ReferenceEquals(this._DataField, value) != true)) {
                    this._DataField = value;
                    this.RaisePropertyChanged("_Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _HelpLink {
            get {
                return this._HelpLinkField;
            }
            set {
                if ((object.ReferenceEquals(this._HelpLinkField, value) != true)) {
                    this._HelpLinkField = value;
                    this.RaisePropertyChanged("_HelpLink");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Middleware.Proxy.CustomEbankit.EbankitCustomService.ServiceException _InnerException {
            get {
                return this._InnerExceptionField;
            }
            set {
                if ((object.ReferenceEquals(this._InnerExceptionField, value) != true)) {
                    this._InnerExceptionField = value;
                    this.RaisePropertyChanged("_InnerException");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _Message {
            get {
                return this._MessageField;
            }
            set {
                if ((object.ReferenceEquals(this._MessageField, value) != true)) {
                    this._MessageField = value;
                    this.RaisePropertyChanged("_Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _Source {
            get {
                return this._SourceField;
            }
            set {
                if ((object.ReferenceEquals(this._SourceField, value) != true)) {
                    this._SourceField = value;
                    this.RaisePropertyChanged("_Source");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _StackTrace {
            get {
                return this._StackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this._StackTraceField, value) != true)) {
                    this._StackTraceField = value;
                    this.RaisePropertyChanged("_StackTrace");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExceptionType", Namespace="http://schemas.datacontract.org/2004/07/eBankit.Business.Entities")]
    public enum ExceptionType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        System = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Application = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Business = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceProgressStatus", Namespace="http://schemas.datacontract.org/2004/07/eBankit.Business.Entities")]
    public enum ServiceProgressStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SF = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Workflow = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TimeOut = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnknownError = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BusinessError = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sucess = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Offline = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SessionTimeOut = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SFSended = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PS2 = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PendingAuthorization = 10,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AliasPositionsWithSession", Namespace="http://schemas.datacontract.org/2004/07/eBankit.Business.Entities.Authentication")]
    [System.SerializableAttribute()]
    public partial class AliasPositionsWithSession : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] PositionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PositionsSequenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SessionIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Positions {
            get {
                return this.PositionsField;
            }
            set {
                if ((object.ReferenceEquals(this.PositionsField, value) != true)) {
                    this.PositionsField = value;
                    this.RaisePropertyChanged("Positions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PositionsSequence {
            get {
                return this.PositionsSequenceField;
            }
            set {
                if ((object.ReferenceEquals(this.PositionsSequenceField, value) != true)) {
                    this.PositionsSequenceField = value;
                    this.RaisePropertyChanged("PositionsSequence");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SessionId {
            get {
                return this.SessionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionIdField, value) != true)) {
                    this.SessionIdField = value;
                    this.RaisePropertyChanged("SessionId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EbankitCustomService.IEbankitCustomService")]
    public interface IEbankitCustomService {
        
        // CODEGEN: Generating message contract since message SampleMethodRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEbankitCustomService/SampleMethod", ReplyAction="http://tempuri.org/IEbankitCustomService/SampleMethodResponse")]
        Middleware.Proxy.CustomEbankit.EbankitCustomService.SampleMethodResponse SampleMethod(Middleware.Proxy.CustomEbankit.EbankitCustomService.SampleMethodRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEbankitCustomService/SampleMethod", ReplyAction="http://tempuri.org/IEbankitCustomService/SampleMethodResponse")]
        System.Threading.Tasks.Task<Middleware.Proxy.CustomEbankit.EbankitCustomService.SampleMethodResponse> SampleMethodAsync(Middleware.Proxy.CustomEbankit.EbankitCustomService.SampleMethodRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SampleMethod", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SampleMethodRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="")]
        public Middleware.Proxy.CustomEbankit.EbankitCustomService.ServiceInputHeader InputHeader;
        
        public SampleMethodRequest() {
        }
        
        public SampleMethodRequest(Middleware.Proxy.CustomEbankit.EbankitCustomService.ServiceInputHeader InputHeader) {
            this.InputHeader = InputHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SampleMethodResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SampleMethodResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="ITCore")]
        public Middleware.Proxy.CustomEbankit.EbankitCustomService.ServiceOutputHeader OutputHeader;
        
        public SampleMethodResponse() {
        }
        
        public SampleMethodResponse(Middleware.Proxy.CustomEbankit.EbankitCustomService.ServiceOutputHeader OutputHeader) {
            this.OutputHeader = OutputHeader;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEbankitCustomServiceChannel : Middleware.Proxy.CustomEbankit.EbankitCustomService.IEbankitCustomService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EbankitCustomServiceClient : System.ServiceModel.ClientBase<Middleware.Proxy.CustomEbankit.EbankitCustomService.IEbankitCustomService>, Middleware.Proxy.CustomEbankit.EbankitCustomService.IEbankitCustomService {
        
        public EbankitCustomServiceClient() {
        }
        
        public EbankitCustomServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EbankitCustomServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EbankitCustomServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EbankitCustomServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Middleware.Proxy.CustomEbankit.EbankitCustomService.SampleMethodResponse Middleware.Proxy.CustomEbankit.EbankitCustomService.IEbankitCustomService.SampleMethod(Middleware.Proxy.CustomEbankit.EbankitCustomService.SampleMethodRequest request) {
            return base.Channel.SampleMethod(request);
        }
        
        public Middleware.Proxy.CustomEbankit.EbankitCustomService.ServiceOutputHeader SampleMethod(Middleware.Proxy.CustomEbankit.EbankitCustomService.ServiceInputHeader InputHeader) {
            Middleware.Proxy.CustomEbankit.EbankitCustomService.SampleMethodRequest inValue = new Middleware.Proxy.CustomEbankit.EbankitCustomService.SampleMethodRequest();
            inValue.InputHeader = InputHeader;
            Middleware.Proxy.CustomEbankit.EbankitCustomService.SampleMethodResponse retVal = ((Middleware.Proxy.CustomEbankit.EbankitCustomService.IEbankitCustomService)(this)).SampleMethod(inValue);
            return retVal.OutputHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Middleware.Proxy.CustomEbankit.EbankitCustomService.SampleMethodResponse> Middleware.Proxy.CustomEbankit.EbankitCustomService.IEbankitCustomService.SampleMethodAsync(Middleware.Proxy.CustomEbankit.EbankitCustomService.SampleMethodRequest request) {
            return base.Channel.SampleMethodAsync(request);
        }
        
        public System.Threading.Tasks.Task<Middleware.Proxy.CustomEbankit.EbankitCustomService.SampleMethodResponse> SampleMethodAsync(Middleware.Proxy.CustomEbankit.EbankitCustomService.ServiceInputHeader InputHeader) {
            Middleware.Proxy.CustomEbankit.EbankitCustomService.SampleMethodRequest inValue = new Middleware.Proxy.CustomEbankit.EbankitCustomService.SampleMethodRequest();
            inValue.InputHeader = InputHeader;
            return ((Middleware.Proxy.CustomEbankit.EbankitCustomService.IEbankitCustomService)(this)).SampleMethodAsync(inValue);
        }
    }
}
